Create infrastructure via CloudFormation

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -6,32 +6,27 @@ Parameters:
   EC2AMI:
     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
     Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
-  Domain:
-    Type: String
-  Certificate:
-    Type: String
-    Description: 'An existing ACM certificate ARN for your domain'
-  CodePipelineBucket:
-    Type: String
-    Description: 'The S3 bucket for CodePipeline artifacts.'
-  GitHubOwner:
-    Type: String
-    Description: 'The username of the source GitHub repo.'
-  GitHubRepo:
-    Type: String
-    Description: 'The source GitHub repo name (without the username).'
-  GitHubBranch:
-    Type: String
-    Default: master
-    Description: 'The source GitHub branch.'
-  GitHubPersonalAccessToken:
-    Type: String
-    NoEcho: true
-    Description: 'A GitHub personal access token with "repo" and "admin:repo_hook" permissions.'
 
 Resources:
-  DeploymentRole:
-    Type: AWS::IAM::Role
+
+  SecurityGroup:
+    Type: "AWS::EC2::SecurityGroup"
+    Properties:
+      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}'
+      SecurityGroupIngress:
+        - IpProtocol: tcp
+          FromPort: 8080
+          ToPort: 8080
+          CidrIp: 0.0.0.0/0
+        - IpProtocol: tcp
+          FromPort: 22
+          ToPort: 22
+          CidrIp: 0.0.0.0/0
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+  InstanceRole:
+    Type: "AWS::IAM::Role"
     Properties:
       AssumeRolePolicyDocument:
         Version: "2012-10-17"
@@ -39,172 +34,95 @@ Resources:
           Effect: Allow
           Principal:
             Service:
-              - codepipeline.amazonaws.com
-              - codedeploy.amazonaws.com
-              - codebuild.amazonaws.com
+              - "ec2.amazonaws.com"
           Action: sts:AssumeRole
       ManagedPolicyArns:
-        - arn:aws:iam::aws:policy/PowerUserAccess
-
-  BuildProject:
-    Type: AWS::CodeBuild::Project
+        - arn:aws:iam::aws:policy/CloudWatchFullAccess
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+  InstanceProfile:
+    Type: "AWS::IAM::InstanceProfile"
     Properties:
-      Name: !Ref AWS::StackName
-      ServiceRole: !GetAtt DeploymentRole.Arn
-      Artifacts:
-        Type: CODEPIPELINE
-      Environment:
-        Type: LINUX_CONTAINER
-        ComputeType: BUILD_GENERAL1_SMALL
-        Image: aws/codebuild/standard:2.0
-      Source:
-        Type: CODEPIPELINE
-
-  DeploymentApplication:
-    Type: AWS::CodeDeploy::Application
+      Roles:
+        - Ref: InstanceRole
+  Instance:
+    Type: AWS::EC2::Instance
+    CreationPolicy: 
+      ResourceSignal:
+        Timeout: PT15M
+        Count: 1
+    Metadata:
+      AWS::CloudFormation::Init:
+        config:
+          packages: 
+            yum:
+              wget: []
+              unzip: []
     Properties:
-      ApplicationName: !Ref AWS::StackName
-      ComputePlatform: Server
+      ImageId: !Ref EC2AMI
+      InstanceType: !Ref EC2InstanceType
+      IamInstanceProfile: !Ref InstanceProfile
+      Monitoring: true
+      SecurityGroupIds:
+        - !GetAtt SecurityGroup.GroupId 
+      UserData:
+        Fn::Base64: !Sub |
+          #!/bin/bash -xe
 
-  StagingDeploymentGroup:
-    Type: AWS::CodeDeploy::DeploymentGroup
-    Properties:
-      DeploymentGroupName: staging
-      AutoScalingGroups:
-        - !GetAtt Staging.Outputs.ScalingGroup
-      ApplicationName: !Ref DeploymentApplication
-      DeploymentConfigName: CodeDeployDefault.AllAtOnce
-      ServiceRoleArn: !GetAtt DeploymentRole.Arn
+          # send script output to /tmp so we can debug boot failures
+          exec > /tmp/userdata.log 2>&1 
 
-  ProdDeploymentGroup:
-    Type: AWS::CodeDeploy::DeploymentGroup
-    Properties:
-      DeploymentGroupName: prod
-      AutoScalingGroups:
-        - !GetAtt Prod.Outputs.ScalingGroup
-      ApplicationName: !Ref DeploymentApplication
-      DeploymentConfigName: CodeDeployDefault.OneAtATime
-      ServiceRoleArn: !GetAtt DeploymentRole.Arn
+          # Update all packages
+          yum -y update
 
-  Pipeline:
-    Type: AWS::CodePipeline::Pipeline
-    Properties:
-      Name: !Ref AWS::StackName
-      ArtifactStore:
-        Location: !Ref CodePipelineBucket
-        Type: S3
-      RoleArn: !GetAtt DeploymentRole.Arn
-      Stages:
-        - Name: Source
-          Actions:
-            - Name: Source
-              ActionTypeId:
-                Category: Source
-                Owner: ThirdParty
-                Version: 1
-                Provider: GitHub
-              OutputArtifacts:
-                - Name: Source
-              Configuration:
-                Owner: !Ref GitHubOwner
-                Repo: !Ref GitHubRepo
-                Branch: !Ref GitHubBranch
-                OAuthToken: !Ref GitHubPersonalAccessToken
-                PollForSourceChanges: false
-              RunOrder: 1
-        - Name: Build
-          Actions:
-            - Name: Build
-              ActionTypeId:
-                Category: Build
-                Owner: AWS
-                Version: 1
-                Provider: CodeBuild
-              InputArtifacts:
-                - Name: Source
-              OutputArtifacts:
-                - Name: Build
-              Configuration:
-                ProjectName: !Ref BuildProject
-              RunOrder: 1
-        - Name: Staging
-          Actions:
-            - Name: Staging
-              InputArtifacts:
-                - Name: Build
-              ActionTypeId:
-                Category: Deploy
-                Owner: AWS
-                Version: 1
-                Provider: CodeDeploy
-              Configuration:
-                ApplicationName: !Ref DeploymentApplication
-                DeploymentGroupName: !Ref StagingDeploymentGroup
-              RunOrder: 1
-        - Name: Prod
-          Actions:
-            - Name: Prod
-              InputArtifacts:
-                - Name: Build
-              ActionTypeId:
-                Category: Deploy
-                Owner: AWS
-                Version: 1
-                Provider: CodeDeploy
-              Configuration:
-                ApplicationName: !Ref DeploymentApplication
-                DeploymentGroupName: !Ref ProdDeploymentGroup
-              RunOrder: 1
+          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+          yum install -y aws-cfn-bootstrap
 
-  PipelineWebhook:
-    Type: AWS::CodePipeline::Webhook
-    Properties:
-      Authentication: GITHUB_HMAC
-      AuthenticationConfiguration:
-        SecretToken: !Ref GitHubPersonalAccessToken
-      Filters:
-        - JsonPath: $.ref
-          MatchEquals: 'refs/heads/{Branch}'
-      TargetPipeline: !Ref Pipeline
-      TargetAction: Source
-      Name: !Sub 'webhook-${AWS::StackName}'
-      TargetPipelineVersion: !GetAtt Pipeline.Version
-      RegisterWithThirdParty: true
+          # Have CloudFormation install any files and packages from the metadata
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance 
 
-  Staging:
-    Type: AWS::CloudFormation::Stack
-    Properties:
-      TemplateURL: stage.yml
-      TimeoutInMinutes: 30
-      Parameters:
-        EC2InstanceType: !Ref EC2InstanceType
-        EC2AMI: !Ref EC2AMI
-        Domain: !Ref Domain
-        SubDomain: staging
-        Certificate: !Ref Certificate
+          cat > /tmp/install_script.sh << EOF 
+            # START
+            echo "Setting up NodeJS Environment"
+            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
 
-  Prod:
-    Type: AWS::CloudFormation::Stack
-    DependsOn: Staging
-    Properties:
-      TemplateURL: stage.yml
-      TimeoutInMinutes: 30
-      Parameters:
-        EC2InstanceType: !Ref EC2InstanceType
-        EC2AMI: !Ref EC2AMI
-        Domain: !Ref Domain
-        SubDomain: prod
-        Certificate: !Ref Certificate
+            # Dot source the files to ensure that variables are available within the current shell
+            . /home/ec2-user/.nvm/nvm.sh
+            . /home/ec2-user/.bashrc
+
+            # Install NVM, NPM, Node.JS
+            nvm alias default v12.7.0
+            nvm install v12.7.0
+            nvm use v12.7.0
+
+            # Download latest code, unzip it into /home/ec2-user/app
+            wget https://github.com/szhounyc/aws-bootstrap2/archive/master.zip 
+            unzip master.zip
+            mv aws-bootstrap2-master app
+
+            # Create log directory
+            mkdir -p /home/ec2-user/app/logs
+
+            # Run server
+            cd app
+            npm install
+            npm start
+          EOF
+
+          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+          sleep 1; su - ec2-user -c "/tmp/install_script.sh" 
+
+          # Signal to CloudFormation that the instance is ready
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance 
+          
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
 
 Outputs:
-  StagingHTTPSLBEndpoint:
-    Description: The DNS name for the staging HTTPS LB
-    Value: !GetAtt Staging.Outputs.HTTPSEndpoint
+  InstanceEndpoint:
+    Description: The DNS name for the created instance
+    Value: !Sub "http://${Instance.PublicDnsName}:8080" 
     Export:
-      Name: StagingHTTPSLBEndpoint
-  ProdHTTPSLBEndpoint:
-    Description: The DNS name for the prod HTTPS LB
-    Value: !GetAtt Prod.Outputs.HTTPSEndpoint
-    Export:
-      Name: ProdHTTPSLBEndpoint
-
+      Name: InstanceEndpoint
